# Travis Continuous Integration Configuration File, based on ..
language:
  - cpp
  - python
python:
  - "2.7"
compiler:
  - gcc
env:
  - ROS_DISTRO=groovy ROSWS=rosws BUILDER="rosmake euslisp roseus roseus_smach roseus_tutorials" BUILDER_TEST="echo rosmake includes test already" BUILDER_INSTALL="echo no install for rosmake"
  - ROS_DISTRO=hydro ROSWS=wstool BUILDER=catkin_make BUILDER_TEST="catkin_make test" BUILDER_INSTALL="catkin_make install"
#notifications:
#  email:
#    recipients:
#      - roseus@jsk.t.u-tokyo.ac.jp
#    on_success: always #[always|never|change] # default: change
#    on_failure: always #[always|never|change] # default: always
before_install: # Use this to prepare the system to install prerequisites or dependencies
  # Define some config vars
  - export CI_SOURCE_PATH=$(pwd)
  - export REPOSITORY_NAME=${PWD##*/}
  - echo "Testing branch $TRAVIS_BRANCH of $REPOSITORY_NAME"
  - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu precise main" > /etc/apt/sources.list.d/ros-latest.list'
  - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y python-catkin-pkg python-rosdep python-wstool ros-$ROS_DISTRO-catkin ros-$ROS_DISTRO-ros python-rosinstall
  # MongoDB hack - I don't fully understand this but its for moveit_warehouse
  - sudo apt-get remove -y mongodb mongodb-10gen
  - sudo apt-get install -y mongodb-clients mongodb-server -o Dpkg::Options::="--force-confdef" # default actions
  ##### quick hack for missing python-tk on hrpsys/waitInput.py
  - sudo apt-get install -qq -y python-tk
  # Setup rosdep
  - sudo rosdep init
  - rosdep update
install: # Use this to install any prerequisites or dependencies necessary to run your build
  # Create workspace
  - source /opt/ros/$ROS_DISTRO/setup.bash
  - mkdir -p ~/ros/ws_$REPOSITORY_NAME/src
  - cd ~/ros/ws_$REPOSITORY_NAME/src
  - $ROSWS init .
  - $ROSWS merge http://raw.github.com/$TRAVIS_REPO_SLUG/$TRAVIS_BRANCH/.rosinstall
  - if [ $ROSWS != wstool ]; $ROSWS merge /opt/ros/$ROS_DISTRO/.rosinstall; fi
  - $ROSWS update
  - if [ $ROSWS != wstool ]; then $ROSWS set --git jsk_roseus https://dummy.com/dummy -y ; fi
  - ln -s $CI_SOURCE_PATH . # Link the repo we are testing to the new workspace
  - cd ../
  # Install dependencies for source repos
  - rosdep install -r -n --from-paths src --ignore-src --rosdistro $ROS_DISTRO -y
before_script: # Use this to prepare your build for testing e.g. copy database configurations, environment variables, etc.
  - source /opt/ros/$ROS_DISTRO/setup.bash
  - if [ $ROSWS != wstool ]; then source src/setup.bash; fi
script: # All commands must exit with code 0 on success. Anything else is considered failure.
  - rospack profile
  - $BUILDER
  - $BUILDER_TEST
  - $BUILDER_INSTALL
  - rm -fr devel src build
  - if [ $BUILDER = catkin_make ]; then source install/setup.bash; fi
  - if [ $BUILDER = catkin_make ]; then find install -iname "*.test" -print0 | xargs -0 -n1 rostest; fi
after_failure:
  - if [ -e ./build/Testing/Temporary/LastTest.log ]; then cat ./build/Testing/Temporary/LastTest.log; fi
  - find ${HOME}/.ros/test_results -type f -exec echo "== {} ==" \; -exec cat {} \;
  - for file in ${HOME}/.ros/log/rostest-*; do echo "=== $file ==="; cat $file; done

